config/routes.rb
Postgresql::Application.routes.draw do
  resources :members

  resources :vehicles

  resources :memeber_ships

  resources :projects

  resources :companies

end

app/models/memeber_ship.rb
class MemeberShip < ActiveRecord::Base
end

# == Schema Information
#
# Table name: memeber_ships
#
#  id         :integer         not null, primary key
#  member_id  :integer
#  project_id :integer
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/memeber_ships_controller.rb
class MemeberShipsController < ApplicationController
  # GET /memeber_ships
  # GET /memeber_ships.xml
  def index
    @memeber_ships = MemeberShip.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @memeber_ships }
    end
  end

  # GET /memeber_ships/1
  # GET /memeber_ships/1.xml
  def show
    @memeber_ship = MemeberShip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @memeber_ship }
    end
  end

  # GET /memeber_ships/new
  # GET /memeber_ships/new.xml
  def new
    @memeber_ship = MemeberShip.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @memeber_ship }
    end
  end

  # GET /memeber_ships/1/edit
  def edit
    @memeber_ship = MemeberShip.find(params[:id])
  end

  # POST /memeber_ships
  # POST /memeber_ships.xml
  def create
    @memeber_ship = MemeberShip.new(params[:memeber_ship])

    respond_to do |format|
      if @memeber_ship.save
        format.html { redirect_to(@memeber_ship, :notice => 'Memeber ship was successfully created.') }
        format.xml  { render :xml => @memeber_ship, :status => :created, :location => @memeber_ship }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @memeber_ship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /memeber_ships/1
  # PUT /memeber_ships/1.xml
  def update
    @memeber_ship = MemeberShip.find(params[:id])

    respond_to do |format|
      if @memeber_ship.update_attributes(params[:memeber_ship])
        format.html { redirect_to(@memeber_ship, :notice => 'Memeber ship was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @memeber_ship.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /memeber_ships/1
  # DELETE /memeber_ships/1.xml
  def destroy
    @memeber_ship = MemeberShip.find(params[:id])
    @memeber_ship.destroy

    respond_to do |format|
      format.html { redirect_to(memeber_ships_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/memeber_ships_helper.rb
module MemeberShipsHelper
end

app/views/memeber_ships/_form.html.erb
<%= form_for(@memeber_ship) do |f| %>
  <% if @memeber_ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memeber_ship.errors.count, "error") %> prohibited this memeber_ship from being saved:</h2>

      <ul>
      <% @memeber_ship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memeber_ships/edit.html.erb
<h1>Editing memeber_ship</h1>

<%= render 'form' %>

<%= link_to 'Show', @memeber_ship %> |
<%= link_to 'Back', memeber_ships_path %>

app/views/memeber_ships/index.html.erb
<h1>Listing memeber_ships</h1>

<table>
  <tr>
    <th>Member</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memeber_ships.each do |memeber_ship| %>
  <tr>
    <td><%= memeber_ship.member_id %></td>
    <td><%= memeber_ship.project_id %></td>
    <td><%= link_to 'Show', memeber_ship %></td>
    <td><%= link_to 'Edit', edit_memeber_ship_path(memeber_ship) %></td>
    <td><%= link_to 'Destroy', memeber_ship, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Memeber ship', new_memeber_ship_path %>

app/views/memeber_ships/new.html.erb
<h1>New memeber_ship</h1>

<%= render 'form' %>

<%= link_to 'Back', memeber_ships_path %>

app/views/memeber_ships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Member:</b>
  <%= @memeber_ship.member_id %>
</p>

<p>
  <b>Project:</b>
  <%= @memeber_ship.project_id %>
</p>


<%= link_to 'Edit', edit_memeber_ship_path(@memeber_ship) %> |
<%= link_to 'Back', memeber_ships_path %>